spring:
  datasource:
    username: root
    password: kate110276
    url: jdbc:mysql://localhost:3306/inventory_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

